/* eslint-disable global-require */
export default {
  logo: require('./images/logoTC.png'),
  home: require('./images/home.png'),
  logout: require('./images/logout.png'),
  files: require('./images/files.png'),
  audit: require('./images/audit.png'),
  star: require('./images/star.png'),
  plus: require('./images/plus.png'),
  Raster: require('./images/Raster.png'),
  calendar: require('./images/calendar.png'),
  right_arrow: require('./images/right-arrow.png'),
  time: require('./images/time.png'),
  pdf3: require('./images/pdf3.png'),
  recycle: require('./images/recycle.png'),
  edit: require('./images/edit.png'),
  bell: require('./images/bell.png'),
  bell_red: require('./images/bell_red.png'),
  search: require('./images/search.png'),
};
