module.exports = {
  Nom: 'invite',
  'Pr�nom': 'invite',
  'Dateder�ponse': '30/01/2020 16:24',
  "NomduMa�tred'ouvrage:": 'LAQUICHE SYLVAIN',
  "Coordonn�esMa�tred'ouvrage#Civilit�:": 'Monsieur',
  "Coordonn�esMa�tred'ouvrage#Nom:": 'LAQUICHE',
  "Coordonn�esMa�tred'ouvrage#Pr�nom:": 'SYLVAIN',
  "Coordonn�esMa�tred'ouvrage#Adresse:": 'Lieu dit Le Sud',
  "Coordonn�esMa�tred'ouvrage#Codepostal:": '24250',
  "Coordonn�esMa�tred'ouvrage#Ville:": 'GROLEJAC',
  "Coordonn�esMa�tred'ouvrage#T�l�phone:": '660666918',
  "Coordonn�esMa�tred'ouvrage#Mail:": 'slaquiche@free.fr',
  'Coordonn�esauditeur:#NOM:': 'CHORT',
  'Coordonn�esauditeur:#Pr�nom:': 'Jean-Luc',
  'Coordonn�esauditeur:#Adrese:': 'Lieu dit Rauly',
  'Coordonn�esauditeur:#Codepostal:': '82200',
  'Coordonn�esauditeur:#Localit�:': 'MONTESQUIEU',
  'Coordonn�esauditeur:#Telfixe:': '',
  'Coordonn�esauditeur:#Portable:': '06 28 06 54 72',
  'Coordonn�esauditeur:#Mail:': 'jean-luc.chort@wanadoo.fr',
  "M�mecoordonnn�esquelema�tred'ouvrage": 'Oui',
  'Adresse:Adresse': '',
  'Adresse:Codepostal': '',
  'Adresse:Ville': '',
  'Adresse:Pays': '',
  'Surfacehabitable(enm�):': '188',
  'Hauteursousplafondmoyenne(enm):': '2.50',
  'Informationscommunes#Commune(saisirlecodepostal)': 'GROLEJAC',
  'Informationscommunes#CodeInseedelacommune': '24207',
  'Informationscommunes#Altitudemoyennedelacommune': '133',
  'Informationscommunes#R�gion': 'AQUITAINE',
  'Informationscommunes#D�partement:': 'DORDOGNE',
  'Informationscommunes#Statutdelacommune:': 'Commune simple',
  'Informationscommunes#Coded�partement:': '24',
  'Informationscommunes#Superficiedelacommune(enhectares):': '1230',
  "Informationscommunes#Populationenmilliersd'hab(en1997):": '0.6',
  'Informationscommunes#Zoneclimatique:': 'H2c',
  'Informationscommunes#Coeffa=': '0.9',
  'Altitude(enm)sansvirgule:': '133',
  Coefficientb: '0.00',
  Type: 'Maison individuelle',
  'Typedebien�tudi�:': 'Maison individuelle',
  Indexbatetudie: '1',
  'Occupant?': 'Propri�taire occupant - R�sidence principale',
  'Ann�edeconstruction:': '2005',
  Expositionauxvents: 'Moyennement expos�',
  'Zonecoti�re': 'Non',
  'Stationm�t�o(saisirlen�ded�partement)': 'BORDEAUX-MERIGNAC',
  'Mur#Code': 'M1',
  'Mur#Couleursurplan': 'Vert',
  'Mur#Typedemur:': 'Mur ext�rieur',
  'Mur#Indexmitoymur': '1',
  "Mur#Localisationdumur?(S'ils'agitd'unpetitboutdemur,mercid'indiquerlapi�cedanslaquelleilestpr�sent)": '',
  'Mur#S�lectiondumur': "Murs en b�ton-Murs en blocs de b�ton creux-0 � 20 cm-Murs isol�s-Pas d'isolation par l'ext�rieur-Absence de doublage brique avec lame d'air",
  'Mur#Famille:': 'Murs en b�ton',
  'Mur#Type:': 'Murs en blocs de b�ton creux',
  'Mur#�paisseurdumur(structure):': '0 � 20',
  'Mur#Isol�ounon?': 'Murs isol�s',
  "Mur#Isolationparl'ext�rieur?": "Pas d'isolation par l'ext�rieur",
  'Mur#Doublagebrique?': "Absence de doublage brique avec lame d'air",
  'Mur#Indexdumur(codificationinterne)?': '196',
  "Mur#�paisseurdel'isolant(encm)?": '10',
  'Mur#Siautre,mercided�crireaussipr�cis�mentquepossiblelacompositiondecemur:': '',
  'Mur#Photo': 'c37739f590639pu428043_20200130142145_32587.jpg',
  'Mur#Commentaires:': '',
  'Sols#Code': 'S1',
  "Sols#Donnantsur:(Pourlespetitessurfacesdesolssp�cifiques,mercid'indiquerleurpositiondanslamaison)": 'Sur vide-sanitaire',
  'Sols#IndexMitoyPlancher': '2',
  'Sols#Localisation:': '',
  'Sols#Typedeplancher:': 'Plancher lourd type entrevous terre-cuite, poutrelles b�ton-Plancher isol�-Autre configuration',
  'Sols#Indexplancher': '29',
  'Sols#Type:': 'Plancher lourd type entrevous terre-cuite, poutrelles b�ton',
  'Sols#Isol�ounon?': 'Plancher isol�',
  "Sols#Typed'isolation": 'Autre configuration',
  "Sols#�paisseurdel'isolant(encm)?": '5',
  'Sols#R�sum�delasaisi:': 'Plancher lourd type entrevous terre-cuite, poutrelles b�ton-Plancher isol�-Autre configuration',
  'Sols#Siautre,mercided�crireaussipr�cis�mentquepossiblelacompositiondeceplancher:': '',
  'Sols#Photo': 'c37739f590639pu428043_20200130142838_34114.jpg',
  'Sols#Commentaires': "L'�paisseur est celle de la dalle compl�te, isolant inconnu",
  'Plafonds#Code': 'T1',
  'Plafonds#Typedeplafond:Comblesperdus=surlocalnonchauff�,Comblesam�nag�s=Rampants': "Sur local autre que d'habitation",
  'Plafonds#Indexmitoyplafonds': '4',
  "Plafonds#Localisation:(Pourlespetitessurfacesdeplafondssp�cifiques,mercid'indiquerleurpositionnementdanslamaison)": '',
  'Plafonds#Typeplafonds': 'Plafonds en plaque de pl�tre-Plafond isol�',
  'Plafonds#Typedeplafonds:': 'Plafonds en plaque de pl�tre',
  'Plafonds#R�sum�delasaisi:': 'Plafonds en plaque de pl�tre-Plafond isol�',
  'Plafonds#Indexplafond:': '31',
  'Plafonds#Isol�oupas?': 'Plafond isol�',
  "Plafonds#�paisseurdel'isolant(encm)?": '30',
  'Plafonds#Siautre,mercided�crireaussipr�cis�mentquepossiblelacompositiondeceplafond:': '',
  'Plafonds#Photo': 'c37739f590639pu428043_20200130143146_34847.jpg|c37739f590639pu428043_20200130143215_35078.jpg|c37739f590639pu428043_20200130143238_35080.jpg|c37739f590639pu428043_20200130143247_35311.jpg',
  'Plafonds#Commentaires:': '',
  'Plancherinter#Designation': '',
  'Plancherinter#Plancherinterm�diairelourdoul�ger?': '',
  'Plancherinter#Photo': '',
  'Plancherinter#Commentaires:': '',
  'Lesmursderefendssonten?': '',
  'Fen�treouporte-fen�tres:#Code': 'F2',
  'Fen�treouporte-fen�tres:#Indexfen�tre:': '2',
  'Fen�treouporte-fen�tres:#Choixdelafen�tre:': 'Sans remplissage argon ou Krypton',
  'Fen�treouporte-fen�tres:#Famille:': 'Fen�tres ou portes Fen�tres',
  'Fen�treouporte-fen�tres:#Typedefen�tres:': 'Fen�tres coulissantes',
  'Fen�treouporte-fen�tres:#Indexfen�tres:': '460',
  'Fen�treouporte-fen�tres:#Mat�riau:': 'PVC',
  'Fen�treouporte-fen�tres:#Typedevitrage:': 'Double vitrage VIR',
  "Fen�treouporte-fen�tres:#Epaisseurdelalamed'air(ouduverrepourleSV):": '10',
  'Fen�treouporte-fen�tres:#Remplissagegaz:': 'Sans remplissage argon ou Krypton',
  'Fen�treouporte-fen�tres:#R�sum�delasaisi:': "Fen�tres ou portes Fen�tres-Fen�tres coulissantes-PVC -Double vitrage VIR-�paisseur de la lame d'air = 10-Sans remplissage argon ou Krypton",
  'Fen�treouporte-fen�tres:#Largeur(enm):': '1.8',
  'Fen�treouporte-fen�tres:#Hauteur(enm):': '2.15',
  'Fen�treouporte-fen�tres:#Fermeture(volet):': 'Volet roul PVC (ep<=12mm)',
  'Fen�treouporte-fen�tres:#Indexfermeture': '4',
  'Fen�treouporte-fen�tres:#Surfacedefen�tredecetype:': '3.87',
  'Fen�treouporte-fen�tres:#Photo': '',
  'Fen�treouporte-fen�tres:#Commentaires:': '',
  'Surfacetotaledefen�tre:': '22.93',
  'Portes:#Codificationporte:': 'P1',
  'Portes:#S�lectiondelaporte': 'Avec double vitrage',
  'Portes:#Indexcodificationouvrants:': '71',
  'Portes:#Indexporte:': '6',
  'Portes:#Famille:': 'Porte simple en bois',
  'Portes:#Type:': 'Avec double vitrage',
  'Portes:#R�sum�delasaisi:': 'Porte simple en bois-Avec double vitrage',
  'Portes:#Donnantsur:': 'Ext�rieur',
  'Portes:#Largeur(enm):': '0.9',
  'Portes:#Hauteur(enm):': '2.15',
  'Portes:#Surfacedelaporte:': '1.94',
  'Portes:#Photo': 'c37739f590639pu428043_20200130153028_11553.jpg',
  'Portes:#Commentaires:': '',
  'Sommedessurfacesdesportes:': '3.44',
  'Chauffage#S�lectiondug�n�rateurdechauffage:': 'Electrique-Convecteur �lectrique NF-G�n�rateur en volume chauff�',
  'Chauffage#Indexg�n�rateurchauffage': '3',
  'Chauffage#Energie?': 'Electrique',
  'Chauffage#Typedeg�n�rateur?': 'Convecteur �lectrique NF',
  'Chauffage#Volumechauff�ouhorsvolumechauff�?': 'G�n�rateur en volume chauff�',
  'Chauffage#R�sum�delasaisi:': 'Electrique-Convecteur �lectrique NF-G�n�rateur en volume chauff�',
  "Chauffage#Typed'emetteur": '',
  'Chauffage#Index�metteurChauffage:': '',
  "Chauffage#Cesyst�mechauffetoutel'habitation?": 'Non',
  'Chauffage#Surfacechauff�parcesyst�me?': '59',
  'Chauffage#Puissance(enkW):': '',
  'Chauffage#Photo': 'c37739f590639pu428043_20200130154417_19232.jpg|c37739f590639pu428043_20200130154423_19234.jpg',
  'Chauffage#Commentaires(marque,mod�le,r�f�rence,...):': '',
  "Pr�senced'unprogrammateur?": 'Oui',
  Photo: '',
  "Pr�senced'unthermostat?": 'Oui',
  'Pr�sencederobinetsthermostatiques?': 'Non',
  "Pr�senced'unesondedetemp�ratureext�rieures?": 'Non',
  'Commentaires:': '',
  "Tableau#S�lectiondelaproductiond'ECS:": 'Electrique-Ballon vertical entre 5 et 15 ans-En volume chauff�',
  'Tableau#IndexECS': '7',
  "Tableau#Energiepourl'ECS?": 'Electrique',
  'Tableau#Type:': 'Ballon vertical entre 5 et 15 ans',
  'Tableau#Enouhorsvolumechauff�?': 'En volume chauff�',
  'Tableau#R�sum�delasaisi:': 'Electrique-Ballon vertical entre 5 et 15 ans-En volume chauff�',
  'Tableau#Marque,Mod�le,R�f:': '',
  'Tableau#Capacit�duballon(enL):': '200',
  'Tableau#Photo': '',
  'Tableau#Commentaires(ECSSolaireouautre):': '',
  'Ventilation:#Typedeventilation': 'Ventilation Mecanique Simple flux-Autor�glables apr�s 1982',
  'Ventilation:#IndexVentilation': '2',
  'Ventilation:#Famille?': 'Ventilation Mecanique Simple flux',
  'Ventilation:#R�f�rence': 'Autor�glables apr�s 1982',
  'Ventilation:#R�sum�delasaisi:': 'Ventilation Mecanique Simple flux-Autor�glables apr�s 1982',
  'Ventilation:#Siconnu,puissancedu(des)ventilateurs(enW):': '',
  'Ventilation:#Nombredesalledebains?': '1',
  "Ventilation:#Nombred'autresalled'eau?": '2',
  'Ventilation:#NombredeWC?': '1',
  'Ventilation:#Photo': 'c37739f590639pu428043_20200130155317_24416.jpg',
  'Ventilation:#Commentaires:': "Les extractions sont pr�sentes dans toutes les pi�ces d'eau, par contre il manque les entr�es d'air sur deux menuiseries ( Bureaux )",
  "Ilyat'iluneinstallationdeclimatisation?": 'Non',
  "Climatisation:#Descriptiondel'installation:": '',
  'Climatisation:#Photo': '',
  'Climatisation:#Commentaires:': '',
  "Yat'iluneinstallationphotovolta�que?": 'Non',
  "Photovolta�que:#Puissancecr�tedel'installation?": '',
  'Photovolta�que:#Installationventil�s?': '',
  'Photovolta�que:#Orientation?': '',
  'Photovolta�que:#Inclinaisondesmodules?': '',
  'Photovolta�que:#Photo': '',
  "Photovolta�que:#Commentaires(nbrpanneaux,surfaced'unpanneau,...):": '',
  "Ilyat'iluneinstallationpourlacuisson?": 'Oui',
  'Tableau#Modedecuisson?': 'Electrique',
  'Tableau#Commentaire:': 'FOUR',
  'Saisiedel��clairage:#Pi�ce:': '',
  'Saisiedel��clairage:#Liste': 'LED',
  'Saisiedel��clairage:#Dur�edevie(enheures):': '70000',
  'Saisiedel��clairage:#RendementLumens/watt': '80',
  'Saisiedel��clairage:#Commentaires': 'Toutes les pi�ces',
  'Saisiedel��clairage:#Photo': '',
  'Saisiedel��clairage:#Case�cochercach�e': 'Oui',
  'Nombredepi�cesaisie': '1',
  "Moyennedeladur�edeviedel'�clairage:": '70000.00',
  'Commentairedur�edevieeclairage': 'Tr�s bon',
  'Moyennedurendementlumineuxdevotre�clairage:': '80.00',
  Commentairerendementlumineux: 'Tr�s bon',
  'Abonnementsetconsommations(Gazet�lectricit�)#Abonnement': '12 kVA',
  'Abonnementsetconsommations(Gazet�lectricit�)#Indexabonnement:': '4',
  'Abonnementsetconsommations(Gazet�lectricit�)#Energie:': 'Electrique',
  "Abonnementsetconsommations(Gazet�lectricit�)#Nomdel'abonnement?": 'Tarif bleu Option de base',
  'Abonnementsetconsommations(Gazet�lectricit�)#Puissancesouscrite?': '12 kVA',
  'Abonnementsetconsommations(Gazet�lectricit�)#Usagedecette�nergie?': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#ConsommationenkWhen2016': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#Consommationeneurosen2016': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#ConsommationenkWHen2017': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#Consommationeneurosen2017': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#ConsommationenkWhen2018': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#Consommationeneurosen2018': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#Photo': '',
  'Abonnementsetconsommations(Gazet�lectricit�)#Commentaires': '',
  "Mercid'indiquericilesconsommationsdestroisderni�resann�esdefioul:": '',
  "Mercid'indiquericilesconsommationsdestroisderni�resann�esdebois:": '',
  'Surfacechauff�e(enm�)?': '188',
  "Nombred'occupants?": '3',
  Agemoyendesoccupants: '50',
  'Temp�raturedeconsigneenchauffe?': '20',
  'Temp�raturedeconsigneenr�duit?': '20',
  'Nombredesemaineinoccupationenp�riodedechauffe?': '0',
  'Nombredesemainesinoccupationhorsp�riodedechauffe?': '0',
  "Nombred'heuredepr�sence/jourlasemaine": '14',
  "Nombred'heuresdepr�sence/jourleWeek-end?": '24',
  'Commentjugez-vousleconfortthermiquedevotrelogementenhiver?': 'Tr�s insatisfaisant',
  'Commentjugez-vousleconfortthermiquedevotrelogementen�t�?': 'Tr�s insatisfaisant',
  'Commentjugez-vousleconfortthermiquedevotrelogementenintersaison?': 'Insatisfaisant',
  "Commentjugez-vouslescourantsd'airind�sirablesetsourcesd'inconfortdevotrelogement?": 'Tr�s insatisfaisant',
  "Commentjugez-vousl'humidit�auseindevotrelogement?": 'Ni satisfaisant ni insatisfaisant',
  "Objectifsdel'�tude:(plusieurschoixpossibles)": "Am�lioration du confort|Economie d'�nergie",
  'Destravauxsont-ilsd�j�envisag�s?': 'Non',
  'Tableau#Liste': '',
  'Tableau#Caract�ristiquestechniques': '',
  'Tableau#Commentaires:': '',
  'Scenariosdetravaux#Scenario1': '',
  'Scenariosdetravaux#Scenario2': '',
  'Scenariosdetravaux#Pr�cisez:': '',
  'Scenariosdetravaux#Scenario3': '',
  'Scenariosdetravaux#Pr�cisez': '',
  'Photodelapagedegarde:': 'c37739f590639pu428043_20200130160425_31117.jpg',
  'Photodelafacadenord:': 'c37739f590639pu428043_20200130161022_34790.jpg',
  'Photodelafa�adeEst:': '',
  'Photodelafa�adeSud:': '',
  'Photodelafa�adeOuest:': 'c37739f590639pu428043_20200130160902_34176.jpg',
  'Photosdiverses#Titre': 'Combles',
  'Photosdiverses#Description': '',
  'Photosdiverses#Photo': '',
  'Vouspouveziciprendreplusieursphotosdesplans.': 'c37739f590639pu428043_20200130161202_36018.jpg',
  "Vouspouvezr�aliserplusieurscroquisdel'habitationavecdesoutilspr�-existants.vouspouvezaussichargerunephotodevotret�l�phoneouenprendreune.": '',
  'Vouspouvezr�alisericiuncroquis�mainlev�eetajouterunephotodevotreappareilouenprendreune.': '',
  'Commentairesdivers#Commentaire': '',
  'Commentairesdivers#Illustration': '',
  'Commentairesdivers#Dessin': '',
  'G�olocalisation': 'Latitude : 45.7708, Longitude : 4.8821',
  DateetHeure: '28/01/2020 11:59',
  "Lesdonn�esdeceformulairessontexlusivementr�serv�es�ThermiConseildanslecadredelar�alisationdel'AuditEnerg�tiquetelqued�finitdanslebondecommande.": 'Je valide',
  "Signaturedel'auditeur": 'c37739f590639su428043_20200130161408_37255.jpg'
}
