version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  node: circleci/node@1.1.6
jobs:
  build-and-test-node:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # - run: npm test
            - run: npm run build
            - run: pwd
            - run: ls
            # - run: npm run sv
workflows:
    build-and-test-node:
      jobs:
        - build-and-test-node
