module.exports = {
  home_title: 'Audit Enérgetique',
  error_mdp: 'Le mot de passe est incorrect.',
  error_email: 'Identifiants est incorrect.',
  not_found: 'User not found',
  invalid_date: 'Invalid date format',
  is_exist: 'Identifiants déjà utilise',
  auth: {
    code: 'Code Postal',
    nom: 'Nom',
    prenom: 'Prenom',
    phone: 'Téléphone portable',
    fix: 'Téléphone fix',
    adress: 'Adresse',
    signTitle: 'Connexion',
    signupTitle: 'Création',
    sign: 'Authentification',
    signUp: 'Création compte',
    succes: 'Ajout avec succèss',
    update_succes: 'Modification avec succèss',
    username: 'Pseudo',
    email: 'Email',
    password: 'Mot de passe',
    user_adm: 'Administrateur',
    user_usr: 'Thermicien',
    role: 'Rôle',
    profil: 'Profile',
    account_type: 'Type Compte',
    edit: 'Modifier',
    identification: 'Identifiant',
  },
};
