module.exports = {
  home_title: 'Compagnie fiduciaire',
  error_mdp: 'Le mot de passe est incorrect.',
  error_email: 'Identifiants est incorrect.',
  not_found: 'User not found',
  invalid_date: 'Invalid date format',
  invalid_rib: 'Invalid rib',
  select_period: 'Choisir la période',
  is_exist: 'Identifiants deja utilise',
  from: 'Du',
  to: 'Au',
  select_rib: 'Choisir RIB',
  find: 'Rechercher',
  operation_trad: {
    rib: 'RIB: ',
    date: 'Date',
    libelle: 'Libelle',
    montant: 'Montant',
    recepe: 'Recettes',
    spent: 'Dépenses',
    recipe_atr: 'recipe',
    spent_atr: 'spent',
    sold: 'SOLDE:   ',
    cancel: 'Retour',
    no_op_saved: 'Aucune opération trouvée',
  },
  auth: {
    signTitle: 'Connexion',
    signupTitle: 'Création',
    sign: 'Authentification',
    signUp: 'Création compte',
    succes: 'Ajout avec success',
    username: 'Pseudo',
    email: 'Email',
    password: 'Mot de passe',
    user_adm: 'Administrateur',
    user_usr: 'Utilisateur',
    role: 'Rôle',
    profil: 'Profile',
    account_type: 'Type Compte',
    edit: 'Modifier',
    identification: 'Identifiant',
  },
};
