module.exports = {
  home_title: 'Compagnie fiduciaire',
  error_mdp: 'Le mot de passe est incorrect.',
  error_email: 'Identifiants est incorrect.',
  not_found: 'User not found',
  find: 'Rechercher',
  auth: {
    signTitle: 'Connexion',
    signupTitle: 'Création',
    sign: 'Authentification',
    signUp: 'Création compte',
    succes: 'Ajout avec success',
    username: 'Pseudo',
    email: 'Email',
    password: 'Mot de passe',
    user_adm: 'Administrateur',
    user_usr: 'Thermicien',
    role: 'Rôle',
    profil: 'Profile',
    account_type: 'Type Compte',
    edit: 'Modifier',
    identification: 'Identifiant',
  },
};
